name: Build and Lint

on:
  push:
    branches:  main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ cppcheck

      - name: Run static analysis
        run: cppcheck --enable=all --inconclusive --quiet --error-exitcode=1 src include

      - name: Build project
        run: |
          mkdir build && cd build
          cmake ..
          make -j$(nproc)

      - name: Run unit tests
        run: |
          cd build
          ctest --output-on-failure
