name: Build and Test

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential cppcheck
    
    - name: Create build directory
      run: mkdir -p build
    
    - name: Configure CMake
      run: |
        cd build
        cmake ..
    
    - name: Build project
      run: |
        cd build
        make
    
    - name: Run tests
      run: |
        cd build
        make test
    
    - name: Run cppcheck
      run: |
        cppcheck --enable=all --inconclusive --quiet -I include src include \
          --suppressions-list=.cppcheck-suppressions \
          --error-exitcode=1